branches:
  - name: master
    protection:
      # Required. Require at least one approving review on a pull request, before merging.
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false

      # Required. Require status checks to pass before merging.
      required_status_checks:
        strict: true
        contexts:
          - test

      # Enforce all configured restrictions for administrators.
      enforce_admins: true

      # Prevent merge commits from being pushed to matching branches
      required_linear_history: false

      # Restrict who can push to this branch. Team and user restrictions are only available for organization-owned repositories.
      restrictions: null
